version: '3'

services:

  api:
    build: api
    volumes:
      - ../../api:/app
      - ${FEATER_DATA_PATH}/build:/data/build
      - ${FEATER_DATA_PATH}/proxyDomain:/data/proxyDomain
      - ${FEATER_DATA_PATH}/asset:/data/asset
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '${FEATER_API_PORT}:3000'
    depends_on:
      - mongo
      - redis
    networks:
      - featerinternal
    container_name: feater_api

  spa:
    build: spa
    volumes:
      - ../../spa:/app
    ports:
      - '${FEATER_SPA_PORT}:4200'
    networks:
      - featerinternal
    container_name: feater_spa

  mongo:
    image: mongo:3.6
    ports:
      - '${FEATER_MONGO_PORT}:27017'
    networks:
      - featerinternal
    container_name: feater_mongo

  redis:
    image: redis:4
    networks:
      - featerinternal
    container_name: feater_redis

  nginx:
    build: nginx
    volumes:
      - ${FEATER_DATA_PATH}/proxyDomain:/etc/nginx/conf.d/proxyDomain
    ports:
      - '${FEATER_NGINX_PORT}:80'
    networks:
      - featerinternal
      - featerproxy
    container_name: feater_nginx

networks:
  featerinternal:
  featerproxy:
