version: '3'

services:

  app:
    image: feater:latest
    volumes:
      - "${FEATER_HOST_PATH_ASSET}:/data/asset"
      - "${FEATER_HOST_PATH_BUILD}:/data/build"
      - "${FEATER_HOST_PATH_KEY}:/data/key"
      - "${FEATER_HOST_PATH_PROXY}:/data/proxy"
      - "${FEATER_HOST_DOCKER_SOCKET_PATH}:/var/run/docker.sock"
    ports:
      - '${FEATER_PORT}:9010'
      - '80:9011'
    environment:
      FEATER_GUEST_PATH_ROOT: "${FEATER_GUEST_PATH_ROOT}"
      FEATER_GUEST_PATH_ASSET: "/data/asset"
      FEATER_GUEST_PATH_BUILD: "/data/build"
      FEATER_GUEST_PATH_KEY: "/data/key"
      FEATER_GUEST_PATH_PROXY: "/data/proxy"
      FEATER_HOST_PATH_BUILD: "${FEATER_HOST_PATH_BUILD}"
      FEATER_HOST_PATH_ASSET: "${FEATER_HOST_PATH_ASSET}"
      FEATER_MONGO_DSN: "${FEATER_MONGO_DSN}"
      FEATER_DOCKER_BINARY_PATH: "/usr/bin/docker"
      FEATER_DOCKER_COMPOSE_BINARY_PATH: "/usr/local/bin/docker-compose"
      FEATER_DOCKER_COMPOSE_HTTP_TIMEOUT: "${FEATER_DOCKER_COMPOSE_HTTP_TIMEOUT}"
      FEATER_CONTAINER_NAME_PREFIX: "${FEATER_CONTAINER_NAME_PREFIX}"
      FEATER_PROXY_DOMAIN_PATTERN: "${FEATER_PROXY_DOMAIN_PATTERN}"
      FEATER_PROXY_NETWORK_NAME: "${COMPOSE_PROJECT_NAME}_proxy"
      FEATER_LOG_LEVEL_CONSOLE: "${FEATER_LOG_LEVEL_CONSOLE}"
      FEATER_LOG_LEVEL_MONGO: "${FEATER_LOG_LEVEL_MONGO}"
    depends_on:
      - mongo
    networks:
      - internal
      - proxy
    restart: unless-stopped

  mongo:
    image: mongo:3.6
    volumes:
      - "${FEATER_MONGO_HOST_PATH_DATA}:/data/db"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
  proxy:
