version: '3'

services:

  api:
    image: feater_api:latest
    volumes:
      - "${FEATER_DATA_PATH}/build:/data/build"
      - "${FEATER_DATA_PATH}/proxyDomain:/data/proxyDomain"
      - "${FEATER_DATA_PATH}/asset:/data/asset"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${FEATER_API_PORT}:3000"
    environment:
      PORT: 3000
    depends_on:
      - mongo
      - redis
    networks:
      - internal
    container_name: feater_api

  spa:
    build: spa
    volumes:
      - "../../spa:/app"
    ports:
      - "${FEATER_SPA_PORT}:4200"
    networks:
      - internal
    container_name: feater_spa

  mongo:
    image: mongo:3.6
    volumes:
      - "mongo_data:/data/db"
    ports:
      - "${FEATER_MONGO_PORT}:27017"
    networks:
      - internal
    container_name: feater_mongo

  redis:
    image: redis:4
    networks:
      - internal
    container_name: feater_redis

  nginx:
    build: nginx
    volumes:
      - "${FEATER_DATA_PATH}/proxyDomain:/etc/nginx/conf.d/proxyDomain"
    ports:
      - "${FEATER_NGINX_PORT}:80"
    networks:
      - internal
      - proxy
    container_name: feater_nginx

networks:
  internal: ~
  proxy: ~

volumes:
  mongo_data: ~
