version: '3'

services:

  api:
    image: feater-api:latest
    volumes:
    - "${FEATER_HOST_PATH_BUILD}:${FEATER_GUEST_PATH_BUILD}"
    - "${FEATER_HOST_PATH_PROXY_DOMAIN}:${FEATER_HOST_PATH_BUILD}"
    - "${FEATER_HOST_PATH_ASSET}:${FEATER_GUEST_PATH_ASSET}"
    - "${FEATER_HOST_DOCKER_SOCKET_PATH}:/var/run/docker.sock"
    environment:
      FEATER_GUEST_PATH_ROOT: "${FEATER_GUEST_PATH_ROOT}"
      FEATER_GUEST_PATH_BUILD: "${FEATER_GUEST_PATH_BUILD}"
      FEATER_GUEST_PATH_PROXY_DOMAIN: "${FEATER_GUEST_PATH_PROXY_DOMAIN}"
      FEATER_GUEST_PATH_ASSET: "${FEATER_GUEST_PATH_ASSET}"
      FEATER_HOST_PATH_BUILD: "${FEATER_HOST_PATH_BUILD}"
      FEATER_HOST_PATH_ASSET: "${FEATER_HOST_PATH_ASSET}"
      FEATER_MONGO_DSN: "${FEATER_MONGO_DSN}"
      FEATER_DOCKER_BINARY_PATH: "${FEATER_DOCKER_BINARY_PATH}"
      FEATER_DOCKER_COMPOSE_BINARY_PATH: "${FEATER_DOCKER_COMPOSE_BINARY_PATH}"
      FEATER_DOCKER_COMPOSE_HTTP_TIMEOUT: "${FEATER_DOCKER_COMPOSE_HTTP_TIMEOUT}"
      FEATER_CONTAINER_NAME_PREFIX: "${FEATER_CONTAINER_NAME_PREFIX}"
      FEATER_PROXY_DOMAIN_PATTERN: "${FEATER_PROXY_DOMAIN_PATTERN}"
      FEATER_PROXY_DOMAIN_NETWORK_NAME: "${FEATER_PROXY_DOMAIN_NETWORK_NAME}"
      FEATER_LOG_LEVEL_CONSOLE: "${FEATER_LOG_LEVEL_CONSOLE}"
      FEATER_LOG_LEVEL_MONGO: "${FEATER_LOG_LEVEL_MONGO}"
    depends_on:
    - mongo
    networks:
    - internal
    container_name: ${COMPOSE_PROJECT_NAME}_api
    restart: unless-stopped

#  spa:
#    build: spa
#    volumes:
#    - "../../spa:/app"
#    ports:
#    - '${FEATER_SPA_PORT}:4200'
#    networks:
#    - internal
#    container_name: feater_spa_prod
#    restart: unless-stopped

  mongo:
    image: mongo:3.6
    volumes:
    - "${FEATER_MONGO_HOST_PATH_DATA}:/data/db"
    networks:
    - internal
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    restart: unless-stopped

#  nginx:
#    build: nginx
#    volumes:
#    - "${FEATER_PROXY_DOMAIN_DATA_PATH}:/etc/nginx/conf.d/proxyDomain"
#    ports:
#    - '${FEATER_NGINX_PORT}:80'
#    networks:
#    - internal
#    - proxy
#    container_name: feater_nginx_prod
#    restart: unless-stopped

networks:
  internal:
#  proxy:
